language: cpp

compiler: 
  - gcc
  - clang

env:
  global:
    - GCC_VERSION="4.8"

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install:
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq "g++-${GCC_VERSION}"; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-${GCC_VERSION}" CC="gcc-${GCC_VERSION}"; fi
  - if [ "$CXX" = "clang++" ]; then sudo apt-get install -qq "libstdc++-${GCC_VERSION}-dev"; fi

before_script:
  - mkdir build
  - cd build
  - cmake ../ -G"Unix Makefiles" -DCMAKE_CXX_COMPILER=$(which $CXX)
  
script:
  - make
